# Generated by Django 3.2.5 on 2021-08-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Profile/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Profile/')),
                ('is_buyer', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('employees_number', models.IntegerField(blank=True, null=True)),
                ('web_site', models.CharField(blank=True, max_length=5080, null=True)),
                ('about_me', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField()),
                ('secondPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.Product')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
