# Generated by Django 3.2.5 on 2021-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210802_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
