# Generated by Django 3.2.5 on 2021-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_profile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
