# Generated by Django 3.2.5 on 2021-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_quantity'),
        ('users', '0007_alter_profile_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
