# Generated by Django 3.2.5 on 2021-08-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Category/')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('quantity', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('comdition', models.CharField(blank=True, max_length=50, null=True)),
                ('SKU', models.IntegerField(blank=True, null=True, unique=True)),
                ('warranty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mark')),
            ],
        ),
    ]
