# Generated by Django 3.2.5 on 2021-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Products/'),
        ),
    ]
