# Generated by Django 3.2.5 on 2021-08-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mark_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comdition',
            new_name='condition',
        ),
    ]
